### ISSUE TITLE
Pivot plugin

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/rwi#5]
As `gulp-responsive` is a much better solution to generating responsive images, I'm pivoting this plugin to assist `gulp-responsive` in generating the CSS Media Queries e.g.

**Image tags:**

```html
<img src="something.png" /> 
```

becomes...

```html
<img src="something.jpg" srcset="something-1200.jpg 1200w, something-800.jpg 800w">
```

**CSS Attributes**

```css
#element { background: url("something.png") }
```

becomes...

```css
#element { background: url("something.png") }
@media (max-width: 1200px) {
    #element { background: url("something-1200.png") }
}
@media (max-width: 800px) {
    #element { background: url("something-800.png") }
}
```
